// Command goanime-gui is a Wails v2 desktop frontend for GoAnime.
// It reuses all of the scraping, episode-resolution and mpv-launching
// logic from the internal packages via internal/guiapi, and renders a
// native webview UI on Windows, macOS and Linux.
package main

import (
	"embed"
	_ "embed"
	"log"

	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/assetserver"
	"github.com/wailsapp/wails/v2/pkg/options/linux"
	"github.com/wailsapp/wails/v2/pkg/options/mac"
	"github.com/wailsapp/wails/v2/pkg/options/windows"
)

// windowsTheme makes the title bar and its minimise/maximise/close buttons
// follow Windows' own light/dark setting, and tints them to match the app's
// palette so the caption does not sit as a stock grey strip above a dark
// page. The colours mirror --bg-elevated / --fg from style.css, and the
// frontend already follows the same system setting through
// prefers-color-scheme, so the two halves change together.
//
// Windows 11 draws the rounded corners and the modern caption buttons for
// any standard window; what actually needed setting is the theme, which is
// what DWMWA_USE_IMMERSIVE_DARK_MODE keys off.
var windowsTheme = &windows.ThemeSettings{
	// Dark: #161a22 bar, #e8eaed text.
	DarkModeTitleBar:          windows.RGB(0x16, 0x1a, 0x22),
	DarkModeTitleBarInactive:  windows.RGB(0x0f, 0x11, 0x15),
	DarkModeTitleText:         windows.RGB(0xe8, 0xea, 0xed),
	DarkModeTitleTextInactive: windows.RGB(0x9a, 0xa0, 0xa6),
	DarkModeBorder:            windows.RGB(0x26, 0x2b, 0x36),
	DarkModeBorderInactive:    windows.RGB(0x26, 0x2b, 0x36),

	// Light: #ffffff bar, #1b1f27 text.
	LightModeTitleBar:          windows.RGB(0xff, 0xff, 0xff),
	LightModeTitleBarInactive:  windows.RGB(0xf5, 0xf6, 0xf8),
	LightModeTitleText:         windows.RGB(0x1b, 0x1f, 0x27),
	LightModeTitleTextInactive: windows.RGB(0x5f, 0x66, 0x72),
	LightModeBorder:            windows.RGB(0xdc, 0xdf, 0xe6),
	LightModeBorderInactive:    windows.RGB(0xdc, 0xdf, 0xe6),
}

//go:embed all:frontend/dist
var assets embed.FS

// appIcon is the window and taskbar icon.
//
// On Windows the icon actually comes from the executable's resource table,
// not from here: rsrc_windows_amd64.syso (generated by go-winres from this
// same PNG) is linked in automatically by `go build`. Linux and macOS have
// no such resource section, so they are handed the bytes at runtime.
//
// To change the icon, replace appicon.png (and winres/appicon.png) and run
// `go generate ./cmd/goanime-gui`. The .syso is committed so a plain
// `go build` on a fresh clone still produces an icon'd binary.
//
// The resource is built from winres/winres.json rather than go-winres'
// `simply` shortcut, because the icon has to be emitted under resource ID
// **3** as well as 1: the Windows shell reads the lowest icon group for
// Explorer and the taskbar, but Wails loads the window icon by the fixed ID
// 3 (winc.AppIconID). With only ID 1 present, the file gets an icon and the
// running window does not.
//
//go:generate go run github.com/tc-hib/go-winres@v0.3.3 make --arch amd64
//go:embed appicon.png
var appIcon []byte

func main() {
	app := NewApp()

	err := wails.Run(&options.App{
		Title:  "GoAnime",
		Width:  1200,
		Height: 800,
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		OnStartup:  app.startup,
		OnShutdown: app.shutdown,
		Windows: &windows.Options{
			// Follow the OS light/dark setting, the same signal the page
			// itself follows through prefers-color-scheme.
			Theme:       windows.SystemDefault,
			CustomTheme: windowsTheme,
			// Mica is deliberately not enabled: Wails only applies a
			// backdrop when WindowIsTranslucent is set, which makes the
			// whole window see-through. Cover art and text would wash out
			// against the desktop, and the material would be hidden behind
			// the opaque page anyway.
			BackdropType: windows.None,
		},
		Linux: &linux.Options{
			Icon: appIcon,
		},
		Mac: &mac.Options{
			About: &mac.AboutInfo{
				Title:   "GoAnime",
				Message: "Assista anime, filmes e séries pelo desktop.",
				Icon:    appIcon,
			},
		},
		Bind: []interface{}{
			app,
		},
	})
	if err != nil {
		log.Fatalln("goanime-gui failed to start:", err)
	}
}
